FROM node:lts-alpine

# 
WORKDIR /app
# Install the project dependencies
COPY package*.json ./
RUN npm install
# Copy the files from the root of the project to the /app directory
COPY . .
# Build the project
RUN npm run build 

# Expose the port
EXPOSE 443
ENV PORT 443

# Run the project
CMD [ "npm", "run", "start", "-p", "443" ]
